services:
  - type: web
    name: bookstore-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /api/health
    autoDeploy: true
    region: oregon 